### ISSUE TITLE
3 updated icons (scumm-monkey / scumm-monkey2 / scumm-indy3)

### ISSUE THREAD

**Issue by Telev78** [scummvm/scummvm-icons#103]
update of these 3 icons 

- scumm-monkey.png
- scumm-monkey2.png
- scumm-indy3.png

[icons.zip](https://github.com/scummvm/scummvm-icons/files/7889011/icons.zip)

**Comment by GandalfTheWhite80** [comment]
@Telev78  are you planing to update other icons? I'm working on the "extra" white pixel - but luckily alphabetically (gob-bambou is the actual one) :-).

**Comment by Telev78** [comment]
@GandalfTheWhite80  i don't know. I have tested the new grid view in ScummVM and the default icon for these games was bad.
So i have rapidly adapted some pictures to the scummvm format.

**Comment by GandalfTheWhite80** [comment]
Your icons a really nice :thumbsup: - I would like to see more of your work :-)

**Comment by GandalfTheWhite80** [comment]
@Telev78 created a pull request with your icons. Hopefully someone will approve it (with committing rights)

**Comment by SupSuper** [comment]
@Telev78 
> @GandalfTheWhite80 i don't know. I have tested the new grid view in ScummVM and the default icon for these games was bad. So i have rapidly adapted some pictures to the scummvm format.

Why is it bad? Is it a technical issue that can be addressed? Something to be discussed with @JenniBee ? I'd rather not stomp on some past contribution without good reason.

If it's purely cosmetic, these icons are provided just for convenience, they can be replaced by the user if they don't like them. I'd rather the focus be on providing a good-enough "default set", since we don't really have an agreed-upon set of guidelines or artists to make everything consistent across the board.

**Comment by GandalfTheWhite80** [comment]
At least the two old monkey icons have some white pixel border against a black background ( not a technical problem but not nice)

**Comment by GandalfTheWhite80** [comment]
Updated monkey 1/2

Pls feel free @Telev78 to make a new issue for indy3 - that would be really n1.
