### ISSUE TITLE
scumm-pajama icon

### ISSUE THREAD

**Issue by Tucky27** [scummvm/scummvm-icons#117]
[scumm-pajama.zip](https://github.com/scummvm/scummvm-icons/files/7974746/scumm-pajama.zip)
![scumm-pajama](https://user-images.githubusercontent.com/61733979/151886110-62c4e46e-4c8e-4fad-8c2f-a877e8b8d515.png)

**Comment by GandalfTheWhite80** [comment]
* around "junior adventure" logo are some leftovers (greenish pixels agains black)
* the l"junior adventure" logo has some half transparent pixels "inside" (maybe leftover of color to alpha?)

Both are not only visible on a very close look. The logo very bright on white background (due to the transparency).

**Comment by Tucky27** [comment]
The issues you mentioned should be resolved now. If there are any other concerns let me know.

**Comment by GandalfTheWhite80** [comment]
No - looks perfect :-)
